<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VAIO" name="Boat Ed Automation Run on Firefox" tests="2" failures="1" timestamp="17 Nov 2016 20:08:02 GMT" time="68.383" errors="0">
  <testcase name="Search_Validation" time="39.785" classname="products.CM.Search_Test">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at products.CM.Search_Test.Search_Validation(Search_Test.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- Search_Validation -->
  <testcase name="SearchWithAllFields" time="65.015" classname="products.CM.Search_Test"/>
</testsuite> <!-- Boat Ed Automation Run on Firefox -->
